### ISSUE TITLE
Removing the tag for an older version has lead to dependent software failing

### ISSUE THREAD

**Issue by karlmutch** [jjeffery/kv#1]
It appears that the tags being exported by this repo have disappeared creating issues for other software modules reusing this package.

Have any tags/releases been recently deleted ?

**Comment by jjeffery** [comment]
@karlmutch Yes, I removed some tags a month or two ago. My sincere apologies, but I had no idea that anyone other than myself was using this repo. I decided to make some breaking changes to the library, and figured that since I was the only one using it, I'd rather fix the breaks in my own code.

I have not done that before, and promise not to do it again. In the meantime, I can put some tags back. Are you using Go modules or dep or something else?

**Comment by karlmutch** [comment]
thanks for putting them back, using dep.

**Comment by jjeffery** [comment]
Can you please confirm which revision you were depending on? By my reckoning, your `Gopkg.toml` will have a stanza that looks something like:

```toml
[[constraint]]
  name = "github.com/jjeffery/kv"
  version = "1.0.0"
```

Also, your `Gopkg.lock` will have a stanza that looks something like:

```toml
[[projects]]
  digest = "1:dc3323cd00beb2b3c36868af28fa142b059359b6385b95fe6545fe5ab03ae37c"
  name = "github.com/jjeffery/kv"
  packages = ["."]
  pruneopts = ""
  revision = "e16ed12583c8a365f8ae714c7564eeef173447dc"
  version = "v1.0"
```

**Comment by karlmutch** [comment]
Hi,  Yes I believe that is it.  Thanks

**Comment by jjeffery** [comment]
@karlmutch I have created a release that you can use. Because of the subsequent breaking changes, I've named it v0.7.0. So you need to update your `Gopkg.toml` to look something like:

```toml
[[constraint]]
  name = "github.com/jjeffery/kv"
  version = "0.7.0"
```

And run a `dep ensure`. I hope that is not too much inconvenience.
